import { AssetRecord, LicenseMetadata } from "../types";

export const PRESET_LICENSES: Record<string, LicenseMetadata> = {
  cc0: {
    id: "lic_cc0",
    licenseName: "CC0 1.0 Universal (Domínio Público)",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    author: "Comunidade Open Source",
    sourceUrl: "https://github.com",
    commercialUse: true,
    redistributionAllowed: true,
    modificationAllowed: true,
    attributionRequired: false,
    localCopyAllowed: true,
    verifiedAt: "2026-09-06",
  },
  mit: {
    id: "lic_mit",
    licenseName: "MIT License",
    licenseUrl: "https://opensource.org/licenses/MIT",
    author: "Projeto Pedi para meu marido & Colaboradores",
    sourceUrl: "https://github.com/magrelone/minha-esposa-pedio",
    commercialUse: true,
    redistributionAllowed: true,
    modificationAllowed: true,
    attributionRequired: true,
    attributionText: "Copyright (c) 2026 Pedi para meu marido",
    localCopyAllowed: true,
    verifiedAt: "2026-09-06",
  },
  cc_by: {
    id: "lic_cc_by",
    licenseName: "Creative Commons Attribution 4.0 (CC BY 4.0)",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    author: "Artistas e Designers Independentes",
    sourceUrl: "https://wincustomize.com",
    commercialUse: true,
    redistributionAllowed: true,
    modificationAllowed: true,
    attributionRequired: true,
    attributionText: "Crédito requerido ao artista original",
    localCopyAllowed: true,
    verifiedAt: "2026-09-06",
  },
  personal_only: {
    id: "lic_personal",
    licenseName: "Apenas para Uso Pessoal (Não Comercial)",
    licenseUrl: "https://deviantart.com",
    author: "Comunidade de Customização",
    sourceUrl: "https://deviantart.com",
    commercialUse: false,
    redistributionAllowed: false,
    modificationAllowed: true,
    attributionRequired: true,
    attributionText: "Somente para fins de customização pessoal e sem fins lucrativos",
    localCopyAllowed: true,
    verifiedAt: "2026-09-06",
  },
};

export const INITIAL_SEED_ASSETS: AssetRecord[] = [
  {
    id: "ast_wp_cute_pink",
    title: "Candy Clouds & Heart Bloom",
    type: "wallpaper",
    previewUrl: "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=600&auto=format&fit=crop&q=80",
    tags: ["cute", "pink", "aesthetic", "pastel"],
    style: "cute",
    license: PRESET_LICENSES.cc0,
    sha256Hash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    compatibility: "SUPPORTED",
  },
  {
    id: "ast_wp_win11_bloom",
    title: "Windows 11 Fluent Bloom Dark",
    type: "wallpaper",
    previewUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80",
    tags: ["windows11", "fluent", "dark", "minimal"],
    style: "windows11",
    license: PRESET_LICENSES.mit,
    sha256Hash: "3f79bb7b435b05321651daefd374cdc681dc06faa65e374e38337b88ca046dea",
    compatibility: "SUPPORTED",
  },
  {
    id: "ast_wp_retro_xp",
    title: "Bliss Nostalgia 4K Remaster",
    type: "wallpaper",
    previewUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&auto=format&fit=crop&q=80",
    tags: ["retro", "xp", "nature", "classic"],
    style: "retro_xp",
    license: PRESET_LICENSES.cc_by,
    sha256Hash: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",
    compatibility: "SUPPORTED",
  },
  {
    id: "ast_fld_pastel",
    title: "Pastel Dream Folder Pack",
    type: "folder",
    previewUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80",
    tags: ["folders", "cute", "pastel", "pack"],
    style: "cute",
    license: PRESET_LICENSES.cc0,
    sha256Hash: "2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae",
    compatibility: "SUPPORTED",
  },
  {
    id: "ast_cur_cute_cat",
    title: "Neko Paw Animated Cursor Set",
    type: "cursor",
    previewUrl: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80",
    tags: ["cursor", "cute", "animated", "cat"],
    style: "cute",
    license: PRESET_LICENSES.cc_by,
    sha256Hash: "fcde2b2edba56bf408601fb721fe9b5c338d10ee429ea04fae5511b68fbf8fb9",
    compatibility: "SUPPORTED",
  },
];
