import { CrosshairItem } from "../types";

export const PROCEDURAL_PRESETS: CrosshairItem[] = [
  {
    id: "preset-classic-green",
    name: "Classic Green",
    description: "A mira clássica dos torneios em verde fluorescente de alta visibilidade.",
    category: "Competitive",
    tags: ["classic", "cs2", "verde", "competitivo"],
    type: "classic",
    author: "Pedi para meu marido",
    favorite: false,
    usageCount: 15,
    createdAt: "2026-09-02",
    updatedAt: "2026-09-02",
    layers: [],
    classicConfig: {
      id: "cg-1",
      name: "Classic Green",
      type: "classic",
      visible: true,
      locked: false,
      opacity: 1,
      x: 0,
      y: 0,
      scale: 1,
      rotation: 0,
      color: "#00ff66",
      size: 14,
      thickness: 2,
      gap: 6,
      dot: false,
      dotSize: 2,
      outline: true,
      outlineThickness: 1,
      outlineColor: "#000000",
      showTop: true,
      showBottom: true,
      showLeft: true,
      showRight: true,
      tStyle: false,
      rounded: false,
    },
  },
  {
    id: "preset-classic-cyan",
    name: "Classic Cyan",
    description: "Excelente contraste em ambientes de pouca luz e tons escuros.",
    category: "Competitive",
    tags: ["classic", "cyan", "contraste"],
    type: "classic",
    author: "Pedi para meu marido",
    favorite: false,
    usageCount: 8,
    createdAt: "2026-09-02",
    updatedAt: "2026-09-02",
    layers: [],
    classicConfig: {
      id: "cc-1",
      name: "Classic Cyan",
      type: "classic",
      visible: true,
      locked: false,
      opacity: 1,
      x: 0,
      y: 0,
      scale: 1,
      rotation: 0,
      color: "#00f0ff",
      size: 12,
      thickness: 2,
      gap: 4,
      dot: false,
      dotSize: 2,
      outline: true,
      outlineThickness: 1,
      outlineColor: "#000000",
      showTop: true,
      showBottom: true,
      showLeft: true,
      showRight: true,
      tStyle: false,
      rounded: false,
    },
  },
  {
    id: "preset-tiny-dot",
    name: "Tiny Dot",
    description: "Ponto cirúrgico minimalista para máxima precisão de headshots.",
    category: "Dot",
    tags: ["dot", "minimal", "precisão"],
    type: "classic",
    author: "Pedi para meu marido",
    favorite: false,
    usageCount: 20,
    createdAt: "2026-09-02",
    updatedAt: "2026-09-02",
    layers: [],
    classicConfig: {
      id: "td-1",
      name: "Tiny Dot",
      type: "classic",
      visible: true,
      locked: false,
      opacity: 1,
      x: 0,
      y: 0,
      scale: 1,
      rotation: 0,
      color: "#00ffcc",
      size: 0,
      thickness: 3,
      gap: 0,
      dot: true,
      dotSize: 3,
      outline: true,
      outlineThickness: 1,
      outlineColor: "#000000",
      showTop: false,
      showBottom: false,
      showLeft: false,
      showRight: false,
      tStyle: false,
      rounded: true,
    },
  },
  {
    id: "preset-precision-dot",
    name: "Precision Dot",
    description: "Ponto com contorno fino e centro translúcido para mirar em pixels distantes.",
    category: "Dot",
    tags: ["dot", "sniper", "precisão"],
    type: "classic",
    author: "Pedi para meu marido",
    favorite: false,
    usageCount: 5,
    createdAt: "2026-09-02",
    updatedAt: "2026-09-02",
    layers: [],
    classicConfig: {
      id: "pd-1",
      name: "Precision Dot",
      type: "classic",
      visible: true,
      locked: false,
      opacity: 1,
      x: 0,
      y: 0,
      scale: 1,
      rotation: 0,
      color: "#ffffff",
      size: 0,
      thickness: 4,
      gap: 0,
      dot: true,
      dotSize: 4,
      outline: true,
      outlineThickness: 1.5,
      outlineColor: "#000000",
      showTop: false,
      showBottom: false,
      showLeft: false,
      showRight: false,
      tStyle: false,
      rounded: true,
    },
  },
  {
    id: "preset-cute-heart",
    name: "Cute Heart 💕",
    description: "Um coração rosa delicado no centro da tela para jogar com amor.",
    category: "Cute",
    tags: ["fofo", "coracao", "rosa", "amor"],
    type: "layered",
    author: "Marido Apaixonado",
    favorite: true,
    usageCount: 42,
    createdAt: "2026-09-02",
    updatedAt: "2026-09-02",
    layers: [
      {
        id: "ch-1",
        name: "Coração Rosa",
        type: "geometry",
        visible: true,
        locked: false,
        opacity: 0.95,
        x: 0,
        y: -2,
        scale: 1,
        rotation: 0,
        color: "#ec4899",
        shape: "heart",
        size: 14,
        thickness: 2,
        hollow: false,
        outline: true,
        outlineThickness: 1,
        outlineColor: "#831843",
      },
      {
        id: "ch-2",
        name: "Ponto Central Branco",
        type: "geometry",
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 2,
        scale: 1,
        rotation: 0,
        color: "#ffffff",
        shape: "dot",
        size: 3,
        thickness: 1,
        hollow: false,
        outline: true,
        outlineThickness: 1,
        outlineColor: "#ec4899",
      },
    ],
  },
  {
    id: "preset-pink-dot",
    name: "Pink Dot 💗",
    description: "Ponto rosa choque super fofinho com contorno escuro e suave.",
    category: "Cute",
    tags: ["rosa", "fofo", "dot"],
    type: "classic",
    author: "Pedi para meu marido",
    favorite: true,
    usageCount: 30,
    createdAt: "2026-09-02",
    updatedAt: "2026-09-02",
    layers: [],
    classicConfig: {
      id: "pnd-1",
      name: "Pink Dot",
      type: "classic",
      visible: true,
      locked: false,
      opacity: 1,
      x: 0,
      y: 0,
      scale: 1,
      rotation: 0,
      color: "#f472b6",
      size: 0,
      thickness: 4,
      gap: 0,
      dot: true,
      dotSize: 4,
      outline: true,
      outlineThickness: 1,
      outlineColor: "#4c0519",
      showTop: false,
      showBottom: false,
      showLeft: false,
      showRight: false,
      tStyle: false,
      rounded: true,
    },
  },
  {
    id: "preset-rgb-cat",
    name: "Gatinho RGB 🐱🌈",
    description: "Gatinho super fofo com borda Arco-Íris RGB animada em tempo real.",
    category: "Cute",
    tags: ["gato", "cat", "rgb", "chroma", "fofo", "animacao"],
    type: "layered",
    author: "Pedi para meu marido",
    favorite: true,
    usageCount: 50,
    createdAt: "2026-09-02",
    updatedAt: "2026-09-02",
    layers: [
      {
        id: "rgb-cat-layer",
        name: "Emoji Gatinho 🐱",
        type: "emoji",
        emoji: "🐱",
        fontSize: 26,
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        scale: 1,
        rotation: 0,
        color: "#ff69b4",
        glow: true,
        glowEffect: "rgb-chroma",
        glowColor: "#ff0055",
        glowRadius: 14,
        animationSpeed: 2.2,
        shadow: true,
      },
    ],
  },
  {
    id: "preset-rgb-cyber",
    name: "Cyberpunk RGB 🎯🌈",
    description: "Linhas táticas clássicas com borda viva que cicla cores RGB continuamente.",
    category: "Competitive",
    tags: ["rgb", "chroma", "cyberpunk", "competitivo"],
    type: "classic",
    author: "Pedi para meu marido",
    favorite: true,
    usageCount: 28,
    createdAt: "2026-09-02",
    updatedAt: "2026-09-02",
    layers: [],
    classicConfig: {
      id: "rgb-c-1",
      name: "Cyberpunk RGB",
      type: "classic",
      visible: true,
      locked: false,
      opacity: 1,
      x: 0,
      y: 0,
      scale: 1,
      rotation: 0,
      color: "#ffffff",
      size: 10,
      thickness: 2,
      gap: 4,
      dot: true,
      dotSize: 2,
      outline: true,
      outlineThickness: 1,
      outlineColor: "#000000",
      showTop: true,
      showBottom: true,
      showLeft: true,
      showRight: true,
      tStyle: false,
      rounded: false,
      glow: true,
      glowEffect: "rgb-chroma",
      glowColor: "#00f0ff",
      glowRadius: 10,
      animationSpeed: 2.5,
    },
  },
  {
    id: "preset-sakura",
    name: "Sakura 🌸",
    description: "Cruz estilizada com pétalas lilás e rosa pastel.",
    category: "Cute",
    tags: ["sakura", "flores", "rosa", "delicado"],
    type: "layered",
    author: "Pedi para meu marido",
    favorite: true,
    usageCount: 25,
    createdAt: "2026-09-02",
    updatedAt: "2026-09-02",
    layers: [
      {
        id: "sk-1",
        name: "Círculo Sakura",
        type: "geometry",
        visible: true,
        locked: false,
        opacity: 0.85,
        x: 0,
        y: 0,
        scale: 1,
        rotation: 0,
        color: "#fbcfe8",
        shape: "hollow-circle",
        size: 9,
        thickness: 2,
        hollow: true,
        outline: true,
        outlineThickness: 1,
        outlineColor: "#be185d",
      },
      {
        id: "sk-2",
        name: "Ponto Floral",
        type: "geometry",
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        scale: 1,
        rotation: 0,
        color: "#ec4899",
        shape: "dot",
        size: 3,
        thickness: 1,
        hollow: false,
        outline: false,
        outlineThickness: 0,
        outlineColor: "#000",
      },
    ],
  },
  {
    id: "preset-circle-dot",
    name: "Circle Dot",
    description: "Círculo vazado em torno de um ponto de mira central.",
    category: "Circle",
    tags: ["circle", "dot", "hollow"],
    type: "layered",
    author: "Pedi para meu marido",
    favorite: false,
    usageCount: 14,
    createdAt: "2026-09-02",
    updatedAt: "2026-09-02",
    layers: [
      {
        id: "cd-1",
        name: "Círculo Externo",
        type: "geometry",
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        scale: 1,
        rotation: 0,
        color: "#00ffcc",
        shape: "hollow-circle",
        size: 10,
        thickness: 1.5,
        hollow: true,
        outline: true,
        outlineThickness: 1,
        outlineColor: "#000000",
      },
      {
        id: "cd-2",
        name: "Ponto Central",
        type: "geometry",
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        scale: 1,
        rotation: 0,
        color: "#ffffff",
        shape: "dot",
        size: 2,
        thickness: 1,
        hollow: false,
        outline: true,
        outlineThickness: 1,
        outlineColor: "#000000",
      },
    ],
  },
  {
    id: "preset-star-cross",
    name: "Star ✨",
    description: "Estrela cintilante de 5 pontas para quem brilha nas partidas.",
    category: "Cute",
    tags: ["estrela", "fofo", "brilho"],
    type: "layered",
    author: "Pedi para meu marido",
    favorite: false,
    usageCount: 18,
    createdAt: "2026-09-02",
    updatedAt: "2026-09-02",
    layers: [
      {
        id: "st-1",
        name: "Estrela Dourada",
        type: "geometry",
        visible: true,
        locked: false,
        opacity: 0.95,
        x: 0,
        y: 0,
        scale: 1,
        rotation: 0,
        color: "#fbbf24",
        shape: "star",
        size: 12,
        thickness: 1,
        hollow: false,
        outline: true,
        outlineThickness: 1,
        outlineColor: "#78350f",
      },
      {
        id: "st-2",
        name: "Ponto Central",
        type: "geometry",
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        scale: 1,
        rotation: 0,
        color: "#ffffff",
        shape: "dot",
        size: 2,
        thickness: 1,
        hollow: false,
        outline: false,
        outlineThickness: 0,
        outlineColor: "#000",
      },
    ],
  },
  {
    id: "preset-diamond",
    name: "Diamond 💎",
    description: "Losango minimalista com contorno cirúrgico.",
    category: "Minimal",
    tags: ["losango", "diamante", "minimal"],
    type: "layered",
    author: "Pedi para meu marido",
    favorite: false,
    usageCount: 11,
    createdAt: "2026-09-02",
    updatedAt: "2026-09-02",
    layers: [
      {
        id: "dm-1",
        name: "Losango Vazado",
        type: "geometry",
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        scale: 1,
        rotation: 0,
        color: "#38bdf8",
        shape: "diamond",
        size: 8,
        thickness: 2,
        hollow: true,
        outline: true,
        outlineThickness: 1,
        outlineColor: "#0369a1",
      },
    ],
  },
  {
    id: "preset-t-crosshair",
    name: "T-Crosshair",
    description: "Estilo T clássico sem a linha superior para visão totalmente desobstruída da cabeça.",
    category: "Competitive",
    tags: ["t-style", "cs2", "competitivo"],
    type: "classic",
    author: "Pedi para meu marido",
    favorite: false,
    usageCount: 9,
    createdAt: "2026-09-02",
    updatedAt: "2026-09-02",
    layers: [],
    classicConfig: {
      id: "tc-1",
      name: "T-Crosshair",
      type: "classic",
      visible: true,
      locked: false,
      opacity: 1,
      x: 0,
      y: 0,
      scale: 1,
      rotation: 0,
      color: "#22c55e",
      size: 10,
      thickness: 2,
      gap: 3,
      dot: true,
      dotSize: 2,
      outline: true,
      outlineThickness: 1,
      outlineColor: "#000000",
      showTop: false,
      showBottom: true,
      showLeft: true,
      showRight: true,
      tStyle: true,
      rounded: false,
    },
  },
  {
    id: "preset-pixel-cross",
    name: "Pixel Cross 👾",
    description: "Estética retrô de jogos 8-bit com linhas nítidas sem anti-aliasing.",
    category: "Funny",
    tags: ["retro", "pixel", "8bit"],
    type: "classic",
    author: "Pedi para meu marido",
    favorite: false,
    usageCount: 7,
    createdAt: "2026-09-02",
    updatedAt: "2026-09-02",
    layers: [],
    classicConfig: {
      id: "px-1",
      name: "Pixel Cross",
      type: "classic",
      visible: true,
      locked: false,
      opacity: 1,
      x: 0,
      y: 0,
      scale: 1,
      rotation: 0,
      color: "#e11d48",
      size: 8,
      thickness: 3,
      gap: 1,
      dot: true,
      dotSize: 3,
      outline: true,
      outlineThickness: 1,
      outlineColor: "#000000",
      showTop: true,
      showBottom: true,
      showLeft: true,
      showRight: true,
      tStyle: false,
      rounded: false,
    },
  },
  {
    id: "preset-brackets-target",
    name: "Corner Brackets",
    description: "Indicadores táticos de canto como um visor futurista de caça aéreo.",
    category: "Experimental",
    tags: ["brackets", "hud", "futurista"],
    type: "layered",
    author: "Pedi para meu marido",
    favorite: false,
    usageCount: 16,
    createdAt: "2026-09-02",
    updatedAt: "2026-09-02",
    layers: [
      {
        id: "cb-1",
        name: "Cantoneiras Táticas",
        type: "geometry",
        visible: true,
        locked: false,
        opacity: 0.9,
        x: 0,
        y: 0,
        scale: 1,
        rotation: 0,
        color: "#10b981",
        shape: "corner-brackets",
        size: 16,
        thickness: 2,
        hollow: true,
        outline: true,
        outlineThickness: 1,
        outlineColor: "#064e3b",
      },
      {
        id: "cb-2",
        name: "Ponto Verde",
        type: "geometry",
        visible: true,
        locked: false,
        opacity: 1,
        x: 0,
        y: 0,
        scale: 1,
        rotation: 0,
        color: "#ffffff",
        shape: "dot",
        size: 2,
        thickness: 1,
        hollow: false,
        outline: true,
        outlineThickness: 1,
        outlineColor: "#000",
      },
    ],
  },
  {
    id: "preset-purple-precision",
    name: "Purple Precision 💜",
    description: "Mira roxa e lilás com equilíbrio harmônico entre foco e delicadeza.",
    category: "Cute",
    tags: ["lilas", "roxo", "fofo"],
    type: "classic",
    author: "Pedi para meu marido",
    favorite: true,
    usageCount: 22,
    createdAt: "2026-09-02",
    updatedAt: "2026-09-02",
    layers: [],
    classicConfig: {
      id: "pp-1",
      name: "Purple Precision",
      type: "classic",
      visible: true,
      locked: false,
      opacity: 1,
      x: 0,
      y: 0,
      scale: 1,
      rotation: 0,
      color: "#c084fc",
      size: 11,
      thickness: 2,
      gap: 3,
      dot: true,
      dotSize: 2,
      outline: true,
      outlineThickness: 1,
      outlineColor: "#3b0764",
      showTop: true,
      showBottom: true,
      showLeft: true,
      showRight: true,
      tStyle: false,
      rounded: true,
    },
  },
];

/**
 * Procedurally generates a fresh, completely randomized yet visually balanced crosshair!
 */
export function generateRandomCrosshair(): CrosshairItem {
  const colors = [
    "#00ff66",
    "#00ffff",
    "#ec4899",
    "#f43f5e",
    "#a855f7",
    "#38bdf8",
    "#fbbf24",
    "#ffffff",
    "#10b981",
  ];
  const color = colors[Math.floor(Math.random() * colors.length)];
  const size = Math.floor(Math.random() * 12) + 6;
  const thickness = Math.floor(Math.random() * 3) + 1;
  const gap = Math.floor(Math.random() * 8) + 1;
  const dot = Math.random() > 0.4;
  const rounded = Math.random() > 0.5;

  return {
    id: `random-${Date.now()}`,
    name: `Mira Mágica #${Math.floor(Math.random() * 900) + 100}`,
    description: "Gerada proceduralmente especialmente para você ✨",
    category: "Custom",
    tags: ["aleatoria", "procedural", "custom"],
    type: "classic",
    author: "Gerador Procedural",
    favorite: false,
    usageCount: 1,
    createdAt: new Date().toISOString().split("T")[0],
    updatedAt: new Date().toISOString().split("T")[0],
    layers: [],
    classicConfig: {
      id: `rc-layer-${Date.now()}`,
      name: "Mira Clássica",
      type: "classic",
      visible: true,
      locked: false,
      opacity: 1,
      x: 0,
      y: 0,
      scale: 1,
      rotation: 0,
      color,
      size,
      thickness,
      gap,
      dot,
      dotSize: thickness,
      outline: true,
      outlineThickness: 1,
      outlineColor: "#000000",
      showTop: true,
      showBottom: true,
      showLeft: true,
      showRight: true,
      tStyle: false,
      rounded,
    },
  };
}
