import { BotDefinition } from "../types";

export const BOT_REGISTRY: BotDefinition[] = [
  {
    id: "roblox-mm2-coin-collector",
    name: "🪙 MM2 Coin Collector",
    game: "Roblox — Murder Mystery 2",
    category: "Visão Computacional & YOLO",
    provider: "andrewwongwong/RobloxBot",
    description:
      "Detecta moedas visíveis na tela e movimenta o personagem em direção a elas. Possui desvio de outros jogadores quando utilizado o modelo com suporte a detecção de personagens.",
    version: "1.0.0",
    icon: "🪙",
    installed: true,
    capabilities: [
      "vision",
      "keyboard",
      "object_detection",
      "movement",
      "models",
      "gpu",
    ],
    requirements: {
      python: ">= 3.8",
      gpuRecommended: true,
      minModelSizeMb: 40,
      description:
        "Exige captura de tela e GPU/CPU compatível para inferência Ultralytics YOLO11 em tempo real.",
    },
    supportedModels: ["yolo11_roblox_official.pt"],
    defaultConfig: {
      weights: "integrations/robloxbot/vendor/bots/mm2_yolo_coin_collector/weights/yolo11_roblox_official.pt",
      device: "auto",
      conf_thres: 0.25,
      iou_thres: 0.45,
      simulation_mode: false,
      send_preview: true,
      preview_fps: 6,
      mode: "coin_only",
      jump_prob: 0.1,
      capture_mode: "auto",
      region: null,
      window_title: "Roblox",
      monitor_index: 0,
    },
  },
  {
    id: "roblox-hanami-spirit-collector",
    name: "🌸 Hanami Spirit Collector",
    game: "Roblox — Distrito de Hanami",
    category: "Visão Computacional & Coleta AFK",
    provider: "Minha Esposa Pediu / Internal",
    description:
      "Patrulha automaticamente as rotas do Distrito de Hanami e absorve espíritos mágicos (Gatinhos Brancos e Pretos) respeitando o delay de permanência de 3 segundos.",
    version: "1.0.0",
    icon: "🌸",
    installed: true,
    capabilities: [
      "vision",
      "keyboard",
      "object_detection",
      "movement",
      "models",
      "gpu",
    ],
    requirements: {
      python: ">= 3.8",
      gpuRecommended: true,
      minModelSizeMb: 5,
      description:
        "Suporta patrulha contínua pelo mapa estático e inferência YOLO11 para ursos brancos (Sakura) e pretos (Kuro) com tratamento para rotação 360° e desfoque à distância.",
    },
    supportedModels: ["yolo11_hanami_spirits.pt", "yolo11_roblox_official.pt"],
    defaultConfig: {
      weights: "integrations/robloxbot/vendor/bots/mm2_yolo_coin_collector/weights/yolo11_hanami_spirits.pt",
      device: "auto",
      conf_thres: 0.28,
      iou_thres: 0.45,
      simulation_mode: false,
      send_preview: true,
      preview_fps: 6,
      mode: "all_spirits",
      jump_prob: 0.05,
      capture_mode: "auto",
      region: null,
      window_title: "Roblox",
      monitor_index: 0,
      collection_dwell_time: 3.0,
      waypoint_route: "circuit_plaza_temple",
      rest_enabled: true,
      work_duration_mins: 10,
      rest_duration_mins: 10,
      patrol_when_empty: true,
      approach_timeout_s: 3.5,
    },
  },
  {
    id: "roblox-blade-ball-parry",
    name: "⚔️ Blade Ball Auto Parry",
    game: "Roblox — Blade Ball",
    category: "Visão & Tempo de Reação",
    provider: "Comunidade / Em breve",
    description:
      "Calcula a trajetória da bola e aciona o bloqueio no timing perfeito através de visão computacional.",
    version: "0.1.0-preview",
    icon: "⚔️",
    installed: false,
    capabilities: ["vision", "keyboard", "object_detection", "gpu"],
    requirements: {
      python: ">= 3.8",
      gpuRecommended: true,
      minModelSizeMb: 20,
      description: "Módulo futuro em preparação.",
    },
    supportedModels: [],
    defaultConfig: {
      weights: "",
      device: "auto",
      conf_thres: 0.3,
      iou_thres: 0.45,
      simulation_mode: true,
      send_preview: true,
      preview_fps: 10,
      mode: "coin_only",
      jump_prob: 0,
      capture_mode: "auto",
      region: null,
      window_title: "Roblox",
      monitor_index: 0,
    },
  },
  {
    id: "desktop-auto-fisher",
    name: "🎣 Desktop Auto Fisher",
    game: "Automação Genérica",
    category: "Automação por Visão",
    provider: "Antigravity Hub",
    description:
      "Pesca automática em qualquer jogo através do reconhecimento do minigame de boia na tela.",
    version: "0.2.0",
    icon: "🎣",
    installed: false,
    capabilities: ["vision", "mouse", "object_detection"],
    requirements: {
      python: ">= 3.8",
      gpuRecommended: false,
      minModelSizeMb: 10,
      description: "Detector leve de templates visuais.",
    },
    supportedModels: [],
    defaultConfig: {
      weights: "",
      device: "cpu",
      conf_thres: 0.5,
      iou_thres: 0.45,
      simulation_mode: true,
      send_preview: true,
      preview_fps: 5,
      mode: "coin_only",
      jump_prob: 0,
      capture_mode: "region",
      region: null,
      window_title: "",
      monitor_index: 0,
    },
  },
];

export function getBotDefinition(id: string): BotDefinition | undefined {
  return BOT_REGISTRY.find((b) => b.id === id);
}
